spring:
  application:
    name: windcore-demo
  profiles:
    active: test
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
      location: D:\\temp
      file-size-threshold: 40KB
  # 内容协商配置
  mvc:
    contentnegotiation:
      favor-parameter: true  # 启用查询参数协商
      parameter-name: format # 参数名称
      favor-path-extension: true # 启用路径扩展协商（不推荐）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: _Lqy0123000!
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      max-lifetime: 1800000
      idle-timeout: 30000
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: # 如果Redis设置了密码，请在这里配置
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
# Jasypt 配置加密
jasypt:
  encryptor:
    # 加密使用的算法
    algorithm: PBEWITHHMACSHA512ANDAES_256
    # 加密器Bean名称
    bean: jasyptStringEncryptor
    # 密钥获取迭代次数
    key-obtention-iterations: 1000
    # 池大小
    pool-size: 1
    # 盐值生成器
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    # 初始化向量生成器
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    # 输出类型
    string-output-type: base64
    # 配置占位符前缀，默认为 ENC(
    property:
      prefix: ENC(
      suffix: )
    password: ${WINDCORE_ENCRYPTOR_PASSWORD}

file:
  upload:
    dir: D:\\temp

# 邮件服务配置
mail:
  # 邮件服务器配置
  smtp:
    host: smtp.qq.com  # QQ邮箱SMTP服务器
    port: 587
    username: your-email@qq.com  # 发送方邮箱
    password: your-app-password   # 邮箱授权码
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.qq.com
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  # 邮件模板配置
  template:
    cache: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/mail/
    suffix: .html
  # 发送配置
  sender:
    name: "企业邮件服务"  # 发送方显示名称
    from: your-email@qq.com  # 发送方邮箱
  # 异步配置
  async:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 100
    thread-name-prefix: "mail-async-"

# SpringDoc OpenAPI 配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    display-operation-id: true
    default-models-expand-depth: 1
    default-model-expand-depth: 1
    doc-expansion: none
    filter: false
    show-extensions: true
    show-common-extensions: true
    try-it-out-enabled: true
    persist-authorization: true
    oauth:
      client-id: your-client-id
      client-secret: your-client-secret
  show-actuator: true
  use-management-port: false
  cache:
    disabled: false