spring:
  application:
    name: windcore-demo
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 20MB    # 单个文件大小限制
      max-request-size: 50MB # 总请求大小限制
  # 内容协商配置
  mvc:
    contentnegotiation:
      favor-parameter: true  # 启用查询参数协商
      parameter-name: format # 参数名称
      favor-path-extension: true # 启用路径扩展协商（不推荐）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: _Lqy0123000!
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      max-lifetime: 1800000
      idle-timeout: 30000

server:
  port: 8081
# Jasypt 配置加密
jasypt:
  encryptor:
    # 加密使用的算法
    algorithm: PBEWITHHMACSHA512ANDAES_256
    # 加密器Bean名称
    bean: jasyptStringEncryptor
    # 密钥获取迭代次数
    key-obtention-iterations: 1000
    # 池大小
    pool-size: 1
    # 盐值生成器
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    # 初始化向量生成器
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    # 输出类型
    string-output-type: base64
    # 配置占位符前缀，默认为 ENC(
    property:
      prefix: ENC(
      suffix: )
    password: ${WINDCORE_ENCRYPTOR_PASSWORD}